updated read me file .md



```
  Downloading Oracle Java 8...
  --2018-01-17 09:32:46--  http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
  Resolving download.oracle.com (download.oracle.com)... 104.91.214.56
  Connecting to download.oracle.com (download.oracle.com)|104.91.214.56|:80... connected.
  HTTP request sent, awaiting response... 302 Moved Temporarily
  Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz [following]
  --2018-01-17 09:32:46--  https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
  Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.39.16.136, 2600:1409:a:39c::2d3e, 2600:1409:a:39e::2d3e
  Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.39.16.136|:443... connected.
  HTTP request sent, awaiting response... 302 Moved Temporarily
  Location: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516181686_af52182dccb9555603c4b4a64e6cfb93 [following]
  --2018-01-17 09:32:46--  http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516181686_af52182dccb9555603c4b4a64e6cfb93
  Connecting to download.oracle.com (download.oracle.com)|104.91.214.56|:80... connected.
  HTTP request sent, awaiting response... 404 Not Found
  2018-01-17 09:32:46 ERROR 404: Not Found.
```

Straight to the point, i  have a textarea on a webpage, that one can write a java code on. On clicking run, a php script gets the java code and passes that to the server using the exec(); command. The docker java container is called on the file, and everything seems to be ok. Even the output gets sent back to the php which then prints it out. The issue now is if the java code has a scanner object to get a user response to a question at run time, how do i append the user input for the docker container to get. 
edited
I just did

```
$ docker pull dockerfile/java
Using default tag: latest
Pulling repository docker.io/dockerfile/java
Error: image dockerfile/java:latest not found
```
Hi
When I run the sh buildOdkcerImage.sh -d, it starts to install fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip with SUCCESS. But whe it sends build context to Docker daemon it returns:

Step 1 : FROM oracle/serverjre:8
Pulling repository docker.io/oracle/serverjre
Error: image oracle/serverjre:8 not found
There was an error building the image.

I googled it and some foruns say the pulling URL (docker.io/oracle/serverjre) has changed. Where do I change this in the sh?